/*
 * XYO RESTful Transaction Enrichment API
 * RESTful API for enriching financial transactions.
 *
 * The version of the OpenAPI document: 2.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package financial.xyo.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import financial.xyo.client.ApiClient;
/**
 * EnrichmentResponse
 */
@JsonPropertyOrder({
  EnrichmentResponse.JSON_PROPERTY_MERCHANT,
  EnrichmentResponse.JSON_PROPERTY_DESCRIPTION,
  EnrichmentResponse.JSON_PROPERTY_CATEGORIES,
  EnrichmentResponse.JSON_PROPERTY_LOGO,
  EnrichmentResponse.JSON_PROPERTY_LOCATION,
  EnrichmentResponse.JSON_PROPERTY_ADDRESS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
public class EnrichmentResponse {
  public static final String JSON_PROPERTY_MERCHANT = "merchant";
  @javax.annotation.Nonnull
  private String merchant;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  @javax.annotation.Nonnull
  private String description;

  public static final String JSON_PROPERTY_CATEGORIES = "categories";
  @javax.annotation.Nonnull
  private List<String> categories = new ArrayList<>();

  public static final String JSON_PROPERTY_LOGO = "logo";
  @javax.annotation.Nonnull
  private String logo;

  public static final String JSON_PROPERTY_LOCATION = "location";
  @javax.annotation.Nonnull
  private String location;

  public static final String JSON_PROPERTY_ADDRESS = "address";
  @javax.annotation.Nonnull
  private String address;

  public EnrichmentResponse() { 
  }

  public EnrichmentResponse merchant(@javax.annotation.Nonnull String merchant) {
    this.merchant = merchant;
    return this;
  }

  /**
   * Merchant is the name of the merchant.
   * @return merchant
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_MERCHANT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getMerchant() {
    return merchant;
  }


  @JsonProperty(value = JSON_PROPERTY_MERCHANT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMerchant(@javax.annotation.Nonnull String merchant) {
    this.merchant = merchant;
  }


  public EnrichmentResponse description(@javax.annotation.Nonnull String description) {
    this.description = description;
    return this;
  }

  /**
   * Description is a brief description of the merchant.
   * @return description
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_DESCRIPTION, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getDescription() {
    return description;
  }


  @JsonProperty(value = JSON_PROPERTY_DESCRIPTION, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDescription(@javax.annotation.Nonnull String description) {
    this.description = description;
  }


  public EnrichmentResponse categories(@javax.annotation.Nonnull List<String> categories) {
    this.categories = categories;
    return this;
  }

  public EnrichmentResponse addCategoriesItem(String categoriesItem) {
    if (this.categories == null) {
      this.categories = new ArrayList<>();
    }
    this.categories.add(categoriesItem);
    return this;
  }

  /**
   * Categories lists categories fitting the description of the merchant.
   * @return categories
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CATEGORIES, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<String> getCategories() {
    return categories;
  }


  @JsonProperty(value = JSON_PROPERTY_CATEGORIES, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCategories(@javax.annotation.Nonnull List<String> categories) {
    this.categories = categories;
  }


  public EnrichmentResponse logo(@javax.annotation.Nonnull String logo) {
    this.logo = logo;
    return this;
  }

  /**
   * Logo is a base64-encoded PNG or JPEG representing the merchant logo.
   * @return logo
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_LOGO, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getLogo() {
    return logo;
  }


  @JsonProperty(value = JSON_PROPERTY_LOGO, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLogo(@javax.annotation.Nonnull String logo) {
    this.logo = logo;
  }


  public EnrichmentResponse location(@javax.annotation.Nonnull String location) {
    this.location = location;
    return this;
  }

  /**
   * Location describes the country and city. May be empty if the API returns null.
   * @return location
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_LOCATION, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getLocation() {
    return location;
  }


  @JsonProperty(value = JSON_PROPERTY_LOCATION, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLocation(@javax.annotation.Nonnull String location) {
    this.location = location;
  }


  public EnrichmentResponse address(@javax.annotation.Nonnull String address) {
    this.address = address;
    return this;
  }

  /**
   * Address describes the exact address of purchase. May be empty if the API returns null.
   * @return address
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ADDRESS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getAddress() {
    return address;
  }


  @JsonProperty(value = JSON_PROPERTY_ADDRESS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAddress(@javax.annotation.Nonnull String address) {
    this.address = address;
  }


  /**
   * Return true if this EnrichmentResponse object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EnrichmentResponse enrichmentResponse = (EnrichmentResponse) o;
    return Objects.equals(this.merchant, enrichmentResponse.merchant) &&
        Objects.equals(this.description, enrichmentResponse.description) &&
        Objects.equals(this.categories, enrichmentResponse.categories) &&
        Objects.equals(this.logo, enrichmentResponse.logo) &&
        Objects.equals(this.location, enrichmentResponse.location) &&
        Objects.equals(this.address, enrichmentResponse.address);
  }

  @Override
  public int hashCode() {
    return Objects.hash(merchant, description, categories, logo, location, address);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EnrichmentResponse {\n");
    sb.append("    merchant: ").append(toIndentedString(merchant)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    categories: ").append(toIndentedString(categories)).append("\n");
    sb.append("    logo: ").append(toIndentedString(logo)).append("\n");
    sb.append("    location: ").append(toIndentedString(location)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `merchant` to the URL query string
    if (getMerchant() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%smerchant%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getMerchant()))));
    }

    // add `description` to the URL query string
    if (getDescription() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sdescription%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDescription()))));
    }

    // add `categories` to the URL query string
    if (getCategories() != null) {
      for (int i = 0; i < getCategories().size(); i++) {
        joiner.add(String.format(java.util.Locale.ROOT, "%scategories%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix),
            ApiClient.urlEncode(ApiClient.valueToString(getCategories().get(i)))));
      }
    }

    // add `logo` to the URL query string
    if (getLogo() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%slogo%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getLogo()))));
    }

    // add `location` to the URL query string
    if (getLocation() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%slocation%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getLocation()))));
    }

    // add `address` to the URL query string
    if (getAddress() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%saddress%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getAddress()))));
    }

    return joiner.toString();
  }
}

