/*
 * XYO RESTful Transaction Enrichment API
 * RESTful API for enriching financial transactions.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package financial.xyo.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for APIError
 */
class APIErrorTest {
    private final APIError model = new APIError();

    /**
     * Model tests for APIError
     */
    @Test
    void testAPIError() {
        // TODO: test APIError
    }

    /**
     * Test the property 'type'
     */
    @Test
    void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'title'
     */
    @Test
    void titleTest() {
        // TODO: test title
    }

    /**
     * Test the property 'status'
     */
    @Test
    void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'detail'
     */
    @Test
    void detailTest() {
        // TODO: test detail
    }

    /**
     * Test the property 'instance'
     */
    @Test
    void instanceTest() {
        // TODO: test instance
    }

}
