/*
 * XYO RESTful Transaction Enrichment API
 * RESTful API for enriching financial transactions.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package financial.xyo.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for EnrichmentResponse
 */
class EnrichmentResponseTest {
    private final EnrichmentResponse model = new EnrichmentResponse();

    /**
     * Model tests for EnrichmentResponse
     */
    @Test
    void testEnrichmentResponse() {
        // TODO: test EnrichmentResponse
    }

    /**
     * Test the property 'merchant'
     */
    @Test
    void merchantTest() {
        // TODO: test merchant
    }

    /**
     * Test the property 'description'
     */
    @Test
    void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'categories'
     */
    @Test
    void categoriesTest() {
        // TODO: test categories
    }

    /**
     * Test the property 'logo'
     */
    @Test
    void logoTest() {
        // TODO: test logo
    }

    /**
     * Test the property 'location'
     */
    @Test
    void locationTest() {
        // TODO: test location
    }

    /**
     * Test the property 'address'
     */
    @Test
    void addressTest() {
        // TODO: test address
    }

}
