/*
 * XYO RESTful Transaction Enrichment API
 * RESTful API for enriching financial transactions.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.xyo.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for EnrichTransactionCollectionResponse
 */
class EnrichTransactionCollectionResponseTest {
    private final EnrichTransactionCollectionResponse model = new EnrichTransactionCollectionResponse();

    /**
     * Model tests for EnrichTransactionCollectionResponse
     */
    @Test
    void testEnrichTransactionCollectionResponse() {
        // TODO: test EnrichTransactionCollectionResponse
    }

    /**
     * Test the property 'id'
     */
    @Test
    void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'link'
     */
    @Test
    void linkTest() {
        // TODO: test link
    }

}
