/*
 * XYO RESTful Transaction Enrichment API
 * RESTful API for enriching financial transactions.
 *
 * The version of the OpenAPI document: 2.0.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package financial.xyo.api;

import financial.xyo.client.ApiClient;
import financial.xyo.client.ApiException;
import financial.xyo.client.ApiResponse;
import financial.xyo.client.Configuration;
import financial.xyo.client.Pair;

import financial.xyo.model.EnrichTransactionCollectionResponse;
import financial.xyo.model.EnrichTransactionsRequestInner;
import financial.xyo.model.EnrichmentCollectionStatusResponse;
import financial.xyo.model.EnrichmentRequest;
import financial.xyo.model.EnrichmentResponse;
import financial.xyo.model.ErrorResponse;
import java.util.UUID;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.io.InputStream;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.io.OutputStream;
import java.net.http.HttpRequest;
import java.nio.channels.Channels;
import java.nio.channels.Pipe;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.time.Duration;

import java.util.ArrayList;
import java.util.StringJoiner;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.function.Consumer;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
public class EnrichmentApi {
  /**
   * Utility class for extending HttpRequest.Builder functionality.
   */
  private static class HttpRequestBuilderExtensions {
    /**
     * Adds additional headers to the provided HttpRequest.Builder. Useful for adding method/endpoint specific headers.
     *
     * @param builder the HttpRequest.Builder to which headers will be added
     * @param headers a map of header names and values to add; may be null
     * @return the same HttpRequest.Builder instance with the additional headers set
     */
    static HttpRequest.Builder withAdditionalHeaders(HttpRequest.Builder builder, Map<String, String> headers) {
        if (headers != null) {
            for (Map.Entry<String, String> entry : headers.entrySet()) {
                builder.header(entry.getKey(), entry.getValue());
            }
        }
        return builder;
    }
  }
  private final HttpClient memberVarHttpClient;
  private final ObjectMapper memberVarObjectMapper;
  private final String memberVarBaseUri;
  private final Consumer<HttpRequest.Builder> memberVarInterceptor;
  private final Duration memberVarReadTimeout;
  private final Consumer<HttpResponse<InputStream>> memberVarResponseInterceptor;
  private final Consumer<HttpResponse<InputStream>> memberVarAsyncResponseInterceptor;

  public EnrichmentApi() {
    this(Configuration.getDefaultApiClient());
  }

  public EnrichmentApi(ApiClient apiClient) {
    memberVarHttpClient = apiClient.getHttpClient();
    memberVarObjectMapper = apiClient.getObjectMapper();
    memberVarBaseUri = apiClient.getBaseUri();
    memberVarInterceptor = apiClient.getRequestInterceptor();
    memberVarReadTimeout = apiClient.getReadTimeout();
    memberVarResponseInterceptor = apiClient.getResponseInterceptor();
    memberVarAsyncResponseInterceptor = apiClient.getAsyncResponseInterceptor();
  }


  protected ApiException getApiException(String operationId, HttpResponse<InputStream> response) throws IOException {
    InputStream responseBody = ApiClient.getResponseBody(response);
    String body = null;
    try {
      body = responseBody == null ? null : new String(responseBody.readAllBytes());
    } finally {
      if (responseBody != null) {
        responseBody.close();
      }
    }
    String message = formatExceptionMessage(operationId, response.statusCode(), body);
    return new ApiException(response.statusCode(), message, response.headers(), body);
  }

  private String formatExceptionMessage(String operationId, int statusCode, String body) {
    if (body == null || body.isEmpty()) {
      body = "[no body]";
    }
    return operationId + " call failed with: " + statusCode + " - " + body;
  }

  /**
   * Download file from the given response.
   *
   * @param response Response
   * @return File
   * @throws ApiException If fail to read file content from response and write to disk
   */
  public File downloadFileFromResponse(HttpResponse<InputStream> response, InputStream responseBody) throws ApiException {
    if (responseBody == null) {
      throw new ApiException(new IOException("Response body is empty"));
    }
    try {
      File file = prepareDownloadFile(response);
      java.nio.file.Files.copy(responseBody, file.toPath(), java.nio.file.StandardCopyOption.REPLACE_EXISTING);
      return file;
    } catch (IOException e) {
      throw new ApiException(e);
    }
  }

  /**
   * <p>Prepare the file for download from the response.</p>
   *
   * @param response a {@link java.net.http.HttpResponse} object.
   * @return a {@link java.io.File} object.
   * @throws java.io.IOException if any.
   */
  private File prepareDownloadFile(HttpResponse<InputStream> response) throws IOException {
    String filename = null;
    java.util.Optional<String> contentDisposition = response.headers().firstValue("Content-Disposition");
    if (contentDisposition.isPresent() && !"".equals(contentDisposition.get())) {
      // Get filename from the Content-Disposition header.
      java.util.regex.Pattern pattern = java.util.regex.Pattern.compile("filename=['\"]?([^'\"\\s]+)['\"]?");
      java.util.regex.Matcher matcher = pattern.matcher(contentDisposition.get());
      if (matcher.find())
        filename = matcher.group(1);
    }
    File file = null;
    if (filename != null) {
      java.nio.file.Path tempDir = java.nio.file.Files.createTempDirectory("swagger-gen-native");
      java.nio.file.Path filePath = java.nio.file.Files.createFile(tempDir.resolve(filename));
      file = filePath.toFile();
      tempDir.toFile().deleteOnExit();   // best effort cleanup
      file.deleteOnExit(); // best effort cleanup
    } else {
      file = java.nio.file.Files.createTempFile("download-", "").toFile();
      file.deleteOnExit(); // best effort cleanup
    }
    return file;
  }

  /**
   * Transaction Enrichment
   * Enrich a single financial transaction synchronously.
   * @param enrichmentRequest Transaction enrichment request payload containing payment text and ISO-3166-1 alpha-2 country code. (required)
   * @param xCorrelationID Unique caller correlation identifier (UUIDv4) for distributed tracing across microservice boundaries. (optional)
   * @param traceparent Standard W3C TraceContext header (version-trace_id-parent_id-trace_flags) for distributed APM tracing. (optional)
   * @return EnrichmentResponse
   * @throws ApiException if fails to make API call
   */
  public EnrichmentResponse enrichTransaction(@javax.annotation.Nonnull EnrichmentRequest enrichmentRequest, @javax.annotation.Nullable UUID xCorrelationID, @javax.annotation.Nullable String traceparent) throws ApiException {
    return enrichTransaction(enrichmentRequest, xCorrelationID, traceparent, null);
  }

  /**
   * Transaction Enrichment
   * Enrich a single financial transaction synchronously.
   * @param enrichmentRequest Transaction enrichment request payload containing payment text and ISO-3166-1 alpha-2 country code. (required)
   * @param xCorrelationID Unique caller correlation identifier (UUIDv4) for distributed tracing across microservice boundaries. (optional)
   * @param traceparent Standard W3C TraceContext header (version-trace_id-parent_id-trace_flags) for distributed APM tracing. (optional)
   * @param headers Optional headers to include in the request
   * @return EnrichmentResponse
   * @throws ApiException if fails to make API call
   */
  public EnrichmentResponse enrichTransaction(@javax.annotation.Nonnull EnrichmentRequest enrichmentRequest, @javax.annotation.Nullable UUID xCorrelationID, @javax.annotation.Nullable String traceparent, Map<String, String> headers) throws ApiException {
    ApiResponse<EnrichmentResponse> localVarResponse = enrichTransactionWithHttpInfo(enrichmentRequest, xCorrelationID, traceparent, headers);
    return localVarResponse.getData();
  }

  /**
   * Transaction Enrichment
   * Enrich a single financial transaction synchronously.
   * @param enrichmentRequest Transaction enrichment request payload containing payment text and ISO-3166-1 alpha-2 country code. (required)
   * @param xCorrelationID Unique caller correlation identifier (UUIDv4) for distributed tracing across microservice boundaries. (optional)
   * @param traceparent Standard W3C TraceContext header (version-trace_id-parent_id-trace_flags) for distributed APM tracing. (optional)
   * @return ApiResponse&lt;EnrichmentResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<EnrichmentResponse> enrichTransactionWithHttpInfo(@javax.annotation.Nonnull EnrichmentRequest enrichmentRequest, @javax.annotation.Nullable UUID xCorrelationID, @javax.annotation.Nullable String traceparent) throws ApiException {
    return enrichTransactionWithHttpInfo(enrichmentRequest, xCorrelationID, traceparent, null);
  }

  /**
   * Transaction Enrichment
   * Enrich a single financial transaction synchronously.
   * @param enrichmentRequest Transaction enrichment request payload containing payment text and ISO-3166-1 alpha-2 country code. (required)
   * @param xCorrelationID Unique caller correlation identifier (UUIDv4) for distributed tracing across microservice boundaries. (optional)
   * @param traceparent Standard W3C TraceContext header (version-trace_id-parent_id-trace_flags) for distributed APM tracing. (optional)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;EnrichmentResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<EnrichmentResponse> enrichTransactionWithHttpInfo(@javax.annotation.Nonnull EnrichmentRequest enrichmentRequest, @javax.annotation.Nullable UUID xCorrelationID, @javax.annotation.Nullable String traceparent, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = enrichTransactionRequestBuilder(enrichmentRequest, xCorrelationID, traceparent, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("enrichTransaction", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<EnrichmentResponse>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        EnrichmentResponse responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<EnrichmentResponse>() {});
        

        return new ApiResponse<EnrichmentResponse>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder enrichTransactionRequestBuilder(@javax.annotation.Nonnull EnrichmentRequest enrichmentRequest, @javax.annotation.Nullable UUID xCorrelationID, @javax.annotation.Nullable String traceparent, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'enrichmentRequest' is set
    if (enrichmentRequest == null) {
      throw new ApiException(400, "Missing the required parameter 'enrichmentRequest' when calling enrichTransaction");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v1/ai/finance/enrichment/transaction";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    if (xCorrelationID != null) {
      localVarRequestBuilder.header("X-Correlation-ID", xCorrelationID.toString());
    }
    if (traceparent != null) {
      localVarRequestBuilder.header("traceparent", traceparent.toString());
    }
    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(enrichmentRequest);
      localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Transaction Enrichments
   * Enrich a collection of financial transactions asynchronously.
   * @param enrichTransactionsRequestInner Array of transaction enrichment requests (minimum 1, maximum 50,000 items) for asynchronous batch processing. (required)
   * @param xApiUser Optional identifier for the API user or tenant. (optional)
   * @param xCorrelationID Unique caller correlation identifier (UUIDv4) for distributed tracing across microservice boundaries. (optional)
   * @param traceparent Standard W3C TraceContext header (version-trace_id-parent_id-trace_flags) for distributed APM tracing. (optional)
   * @return EnrichTransactionCollectionResponse
   * @throws ApiException if fails to make API call
   */
  public EnrichTransactionCollectionResponse enrichTransactions(@javax.annotation.Nonnull List<EnrichTransactionsRequestInner> enrichTransactionsRequestInner, @javax.annotation.Nullable String xApiUser, @javax.annotation.Nullable UUID xCorrelationID, @javax.annotation.Nullable String traceparent) throws ApiException {
    return enrichTransactions(enrichTransactionsRequestInner, xApiUser, xCorrelationID, traceparent, null);
  }

  /**
   * Transaction Enrichments
   * Enrich a collection of financial transactions asynchronously.
   * @param enrichTransactionsRequestInner Array of transaction enrichment requests (minimum 1, maximum 50,000 items) for asynchronous batch processing. (required)
   * @param xApiUser Optional identifier for the API user or tenant. (optional)
   * @param xCorrelationID Unique caller correlation identifier (UUIDv4) for distributed tracing across microservice boundaries. (optional)
   * @param traceparent Standard W3C TraceContext header (version-trace_id-parent_id-trace_flags) for distributed APM tracing. (optional)
   * @param headers Optional headers to include in the request
   * @return EnrichTransactionCollectionResponse
   * @throws ApiException if fails to make API call
   */
  public EnrichTransactionCollectionResponse enrichTransactions(@javax.annotation.Nonnull List<EnrichTransactionsRequestInner> enrichTransactionsRequestInner, @javax.annotation.Nullable String xApiUser, @javax.annotation.Nullable UUID xCorrelationID, @javax.annotation.Nullable String traceparent, Map<String, String> headers) throws ApiException {
    ApiResponse<EnrichTransactionCollectionResponse> localVarResponse = enrichTransactionsWithHttpInfo(enrichTransactionsRequestInner, xApiUser, xCorrelationID, traceparent, headers);
    return localVarResponse.getData();
  }

  /**
   * Transaction Enrichments
   * Enrich a collection of financial transactions asynchronously.
   * @param enrichTransactionsRequestInner Array of transaction enrichment requests (minimum 1, maximum 50,000 items) for asynchronous batch processing. (required)
   * @param xApiUser Optional identifier for the API user or tenant. (optional)
   * @param xCorrelationID Unique caller correlation identifier (UUIDv4) for distributed tracing across microservice boundaries. (optional)
   * @param traceparent Standard W3C TraceContext header (version-trace_id-parent_id-trace_flags) for distributed APM tracing. (optional)
   * @return ApiResponse&lt;EnrichTransactionCollectionResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<EnrichTransactionCollectionResponse> enrichTransactionsWithHttpInfo(@javax.annotation.Nonnull List<EnrichTransactionsRequestInner> enrichTransactionsRequestInner, @javax.annotation.Nullable String xApiUser, @javax.annotation.Nullable UUID xCorrelationID, @javax.annotation.Nullable String traceparent) throws ApiException {
    return enrichTransactionsWithHttpInfo(enrichTransactionsRequestInner, xApiUser, xCorrelationID, traceparent, null);
  }

  /**
   * Transaction Enrichments
   * Enrich a collection of financial transactions asynchronously.
   * @param enrichTransactionsRequestInner Array of transaction enrichment requests (minimum 1, maximum 50,000 items) for asynchronous batch processing. (required)
   * @param xApiUser Optional identifier for the API user or tenant. (optional)
   * @param xCorrelationID Unique caller correlation identifier (UUIDv4) for distributed tracing across microservice boundaries. (optional)
   * @param traceparent Standard W3C TraceContext header (version-trace_id-parent_id-trace_flags) for distributed APM tracing. (optional)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;EnrichTransactionCollectionResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<EnrichTransactionCollectionResponse> enrichTransactionsWithHttpInfo(@javax.annotation.Nonnull List<EnrichTransactionsRequestInner> enrichTransactionsRequestInner, @javax.annotation.Nullable String xApiUser, @javax.annotation.Nullable UUID xCorrelationID, @javax.annotation.Nullable String traceparent, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = enrichTransactionsRequestBuilder(enrichTransactionsRequestInner, xApiUser, xCorrelationID, traceparent, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("enrichTransactions", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<EnrichTransactionCollectionResponse>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        EnrichTransactionCollectionResponse responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<EnrichTransactionCollectionResponse>() {});
        

        return new ApiResponse<EnrichTransactionCollectionResponse>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder enrichTransactionsRequestBuilder(@javax.annotation.Nonnull List<EnrichTransactionsRequestInner> enrichTransactionsRequestInner, @javax.annotation.Nullable String xApiUser, @javax.annotation.Nullable UUID xCorrelationID, @javax.annotation.Nullable String traceparent, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'enrichTransactionsRequestInner' is set
    if (enrichTransactionsRequestInner == null) {
      throw new ApiException(400, "Missing the required parameter 'enrichTransactionsRequestInner' when calling enrichTransactions");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v1/ai/finance/enrichment/transactions";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    if (xApiUser != null) {
      localVarRequestBuilder.header("x-api-user", xApiUser.toString());
    }
    if (xCorrelationID != null) {
      localVarRequestBuilder.header("X-Correlation-ID", xCorrelationID.toString());
    }
    if (traceparent != null) {
      localVarRequestBuilder.header("traceparent", traceparent.toString());
    }
    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(enrichTransactionsRequestInner);
      localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Transaction Enrichments Status
   * Get the status of an asynchronous bulk enrichment job.
   * @param id The unique identifier of the asynchronous bulk enrichment job. (required)
   * @param xApiUser Optional identifier for the API user or tenant. (optional)
   * @param xCorrelationID Unique caller correlation identifier (UUIDv4) for distributed tracing across microservice boundaries. (optional)
   * @param traceparent Standard W3C TraceContext header (version-trace_id-parent_id-trace_flags) for distributed APM tracing. (optional)
   * @return EnrichmentCollectionStatusResponse
   * @throws ApiException if fails to make API call
   */
  public EnrichmentCollectionStatusResponse getEnrichmentStatus(@javax.annotation.Nonnull String id, @javax.annotation.Nullable String xApiUser, @javax.annotation.Nullable UUID xCorrelationID, @javax.annotation.Nullable String traceparent) throws ApiException {
    return getEnrichmentStatus(id, xApiUser, xCorrelationID, traceparent, null);
  }

  /**
   * Transaction Enrichments Status
   * Get the status of an asynchronous bulk enrichment job.
   * @param id The unique identifier of the asynchronous bulk enrichment job. (required)
   * @param xApiUser Optional identifier for the API user or tenant. (optional)
   * @param xCorrelationID Unique caller correlation identifier (UUIDv4) for distributed tracing across microservice boundaries. (optional)
   * @param traceparent Standard W3C TraceContext header (version-trace_id-parent_id-trace_flags) for distributed APM tracing. (optional)
   * @param headers Optional headers to include in the request
   * @return EnrichmentCollectionStatusResponse
   * @throws ApiException if fails to make API call
   */
  public EnrichmentCollectionStatusResponse getEnrichmentStatus(@javax.annotation.Nonnull String id, @javax.annotation.Nullable String xApiUser, @javax.annotation.Nullable UUID xCorrelationID, @javax.annotation.Nullable String traceparent, Map<String, String> headers) throws ApiException {
    ApiResponse<EnrichmentCollectionStatusResponse> localVarResponse = getEnrichmentStatusWithHttpInfo(id, xApiUser, xCorrelationID, traceparent, headers);
    return localVarResponse.getData();
  }

  /**
   * Transaction Enrichments Status
   * Get the status of an asynchronous bulk enrichment job.
   * @param id The unique identifier of the asynchronous bulk enrichment job. (required)
   * @param xApiUser Optional identifier for the API user or tenant. (optional)
   * @param xCorrelationID Unique caller correlation identifier (UUIDv4) for distributed tracing across microservice boundaries. (optional)
   * @param traceparent Standard W3C TraceContext header (version-trace_id-parent_id-trace_flags) for distributed APM tracing. (optional)
   * @return ApiResponse&lt;EnrichmentCollectionStatusResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<EnrichmentCollectionStatusResponse> getEnrichmentStatusWithHttpInfo(@javax.annotation.Nonnull String id, @javax.annotation.Nullable String xApiUser, @javax.annotation.Nullable UUID xCorrelationID, @javax.annotation.Nullable String traceparent) throws ApiException {
    return getEnrichmentStatusWithHttpInfo(id, xApiUser, xCorrelationID, traceparent, null);
  }

  /**
   * Transaction Enrichments Status
   * Get the status of an asynchronous bulk enrichment job.
   * @param id The unique identifier of the asynchronous bulk enrichment job. (required)
   * @param xApiUser Optional identifier for the API user or tenant. (optional)
   * @param xCorrelationID Unique caller correlation identifier (UUIDv4) for distributed tracing across microservice boundaries. (optional)
   * @param traceparent Standard W3C TraceContext header (version-trace_id-parent_id-trace_flags) for distributed APM tracing. (optional)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;EnrichmentCollectionStatusResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<EnrichmentCollectionStatusResponse> getEnrichmentStatusWithHttpInfo(@javax.annotation.Nonnull String id, @javax.annotation.Nullable String xApiUser, @javax.annotation.Nullable UUID xCorrelationID, @javax.annotation.Nullable String traceparent, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getEnrichmentStatusRequestBuilder(id, xApiUser, xCorrelationID, traceparent, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("getEnrichmentStatus", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<EnrichmentCollectionStatusResponse>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        EnrichmentCollectionStatusResponse responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<EnrichmentCollectionStatusResponse>() {});
        

        return new ApiResponse<EnrichmentCollectionStatusResponse>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getEnrichmentStatusRequestBuilder(@javax.annotation.Nonnull String id, @javax.annotation.Nullable String xApiUser, @javax.annotation.Nullable UUID xCorrelationID, @javax.annotation.Nullable String traceparent, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'id' is set
    if (id == null) {
      throw new ApiException(400, "Missing the required parameter 'id' when calling getEnrichmentStatus");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v1/ai/finance/enrichment/status/{id}"
        .replace("{id}", ApiClient.urlEncode(id.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    if (xApiUser != null) {
      localVarRequestBuilder.header("x-api-user", xApiUser.toString());
    }
    if (xCorrelationID != null) {
      localVarRequestBuilder.header("X-Correlation-ID", xCorrelationID.toString());
    }
    if (traceparent != null) {
      localVarRequestBuilder.header("traceparent", traceparent.toString());
    }
    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

}
