/*
 * XYO RESTful Transaction Enrichment API
 * RESTful API for enriching financial transactions.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.xyo.api;

import com.xyo.client.ApiException;
import com.xyo.model.EnrichTransactionCollectionResponse;
import com.xyo.model.EnrichTransactionsRequestInner;
import com.xyo.model.EnrichmentCollectionStatusResponse;
import com.xyo.model.EnrichmentRequest;
import com.xyo.model.EnrichmentResponse;
import com.xyo.model.ErrorResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;


/**
 * API tests for EnrichmentApi
 */
@Disabled
public class EnrichmentApiTest {

    private final EnrichmentApi api = new EnrichmentApi();

    
    /**
     * Transaction Enrichment
     *
     * Enrich a single financial transaction synchronously.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void enrichTransactionTest() throws ApiException {
        EnrichmentRequest enrichmentRequest = null;
        EnrichmentResponse response = 
        api.enrichTransaction(enrichmentRequest);
        
        // TODO: test validations
    }
    
    /**
     * Transaction Enrichments
     *
     * Enrich a collection of financial transactions asynchronously.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void enrichTransactionsTest() throws ApiException {
        Object xApiUser = null;
        List<EnrichTransactionsRequestInner> enrichTransactionsRequestInner = null;
        EnrichTransactionCollectionResponse response = 
        api.enrichTransactions(xApiUser, enrichTransactionsRequestInner);
        
        // TODO: test validations
    }
    
    /**
     * Transaction Enrichments Status
     *
     * Get the status of an asynchronous bulk enrichment job.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getEnrichmentStatusTest() throws ApiException {
        String id = null;
        Object xApiUser = null;
        EnrichmentCollectionStatusResponse response = 
        api.getEnrichmentStatus(id, xApiUser);
        
        // TODO: test validations
    }
    
}
